FROM raspbian/stetch

WORKDIR /shirka_voice

# copy all local files to WORKDIR
COPY . .

# If you are building your code for production
# RUN npm install --only=production
RUN npm install

## EXPOSE 8080

CMD ["npm", "run", "start_shirka_voice"]